config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'users#index'

  namespace :api do
    resources :users do
      resources :questions, only: [:show] do
        resources :answers
      end
    end
    resources :teams do
      resources :questions, only: [:index] do
        resources :answers, only: [:index, :show]
      end
    end

    get 'organizations/:organization_id/answers' => 'organizations#index'

    resources :organizations do
      resources :teams
    end

    resources :users do
      resource :team
    end
    resources :teams do
      resources :answers
    end
    resources :questions do
      resources :answers
    end
  end

  resources :organizations do
    resources :teams, only: [:index, :show]
  end

  resources :answers

  resources :questions do
    resources :answers
  end

  resources :teams do
    resources :questions
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email, case_sensitive: false
  validates_format_of :email, with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :description, length: { maximum: 140 }

  belongs_to :team
  has_one :organization, through: :team
  has_many :answers

  def fullname
    "#{first_name} #{last_name}"
  end

  def no_standup_message
    if all_answered_today?
      'Your next standup is tomorrow at ' + organization.start.strftime("%H:%M") + '.'
    else
      'Your next standup is today at ' + organization.start.strftime("%H:%M") + '.'
    end
  end

  def local_time
    team.time_zone.now
  end

  def local_zone
    team.time_zone
  end

  def time_here(time)
    time.in_time_zone(local_zone)
  end

  def last_answer_time
    answers.last.updated_at
  end

  def question_time?
    local_time.time.strftime("%H%M%S") > organization.start.strftime("%H%M%S")
  end

  def today_date
    local_time.strftime("%d")
  end

  def today_month
    local_time.strftime("%m")
  end

  def today_year
    local_time.strftime("%Y")
  end

  def answered_today?(question_id)
    this_answers = Answer.where(user_id: id, question_id: question_id)
    this_answers.each do |a|
      if a.date_local(local_zone) == today_date && a.month_local(local_zone) == today_month && a.year_local(local_zone) == today_year
        return true
        break
      end
    end
    return false
  end

  def all_answered_today?
    organization.questions.each do |q|
      unless answered_today?(q.id)
        return false
      end
    end
    true
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      @organization = current_user.organization
      @last_answers = @organization.answers.last(10).reverse
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_loginhome.html.erb
<div class="user-stats columns small-8">
  <h4 class="user-name"><%= "Hello, #{current_user.fullname}." %></h4>
  <p><%= "Current Location: #{current_user.team.location}" %></p>
</div>

<div class="live-feed columns small-6">
  <h4 class="team-section">Recent Activity in <%= current_user.organization.name %></h4>
    <div class="org-activity-appendable" id="org-activity-appendable">
  </div>
</div>

 <% if current_user.question_time? && !current_user.all_answered_today? %>
  <%= render 'question' %>
<% else %>
  <%= current_user.no_standup_message %>
<% end %>


<div id="org-id" style="display:none"><%= current_user.organization.id %></div>
<div id="team-zone" style="display:none"><%= current_user.team.timezone %></div>
<div id='team-id' style="display:none"><%= current_user.team.id %></div>

<div id="hidden-id" style="display:none"><% if !@last_answers.first.nil? %><%= @last_answers.first.id %><% end %></div>
</div>

app/views/users/_logouthome.html.erb
<h2 class="intro-header">Welcome to StandDown.</h2>
<h4 class="intro-header">What is StandDown, exactly?</h4>
<div id="app"></div>

<div class="intro-container">
<p class="intro-body">
  Standups are vital to the day-to-day operations of tech companies all around the world.
  As these companies grow, however, they often begin opening branches and offices in many differen time zones,
  making standups difficult to schedule. StandDown solves that problem by introducing asynchronous standups.
  Companies and organizations worldwide will be able to get the same information from a standup without having to
   worry about staying late or getting in early.
</p>
</div>

<h4 class="intro-header">How does it work?</h4>
<div class="intro-container">
<p class="intro-body">
  Companies within StandDown set questions and a start time which apply to all members of that company. Each company then has an unlimited number of teams,
   each with their own members, location, and timezone. Every day, at the global start time, all members of a team are prompted to enter their
    responses to the company's worldwide standup questions at the start time in their local time zone. As soon as they've responded, their answers
    go are available to any other member of their organization. The start time varies based on time zone.
</p>
<p class="intro-body">
  For example, imagine that a company sets its start time to 9:00 in the morning. A member of a team in Boston will get prompted to do their standup
  and answer their questions at 9:00 EST. Later in the day, a team in the same company in San Francisco gets their questions at 9:00 PST, and their responses
   immediately go live for the Boston team at 12:00 EST. Likewise, if a team member working in Honolulu happens to be online, they'll see the San Fransisco
    team's responses as soon as they roll in around 6:00 HST, but won't be able to answer questions until 9:00 HST.
</p>
</div>

app/views/users/_question.html.erb
<div class="standup">
<h4 class="subtitle"> <%= link_to current_user.team.date_readable, current_user.organization %> </h4>
<% current_user.team.questions.each do |q| %>

  <% if current_user.answered_today?(q.id) %>

  <h5 class="question"><%= link_to q.body, new_question_answer_path(q), id: q.id %></h5>
  <div class="new-answer" id= <%="response-#{q.id}"%> >
    <h5><%= Answer.where(user: current_user, question: q).last.body %></h5>
  </div>

  <% else %>
    <h5 class="question" onclick="formOpen()" ><%= link_to q.body, new_question_answer_path(q), id: q.id %> </h5>
      <div class="question-form user-questions" style="display: none" id=<%="answer-#{q.id}"%> >
        <div class="row collapse">
          <div class="small-10 columns">
            <input name="answer" type="text" required placeholder="200 Characters Max" id=<%="#{q.id}-value"%> >
          </div>
          <div class="small-2 columns postfix">
            <a href="#" onClick="questionSubmit()" class="button postfix" id=<%="#{q.id}-#{current_user.id}"%> >Answer</a>
          </div>
        </div>
      </div>
    <div class="new-answer" style="display:none" id= <%="response-#{q.id}"%> ></div>
  <% end %>

<% end %>
</div>

app/views/users/index.html.erb
<div class="user-wrapper">
  <%= react_component('liveFeed', {}, {}) %>
  <% if current_user %>
    <%= render 'loginhome' %>
  <% else %>
    <%= render 'logouthome' %>
  <% end %>
</div>