config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'users#index'

  namespace :api do
    resources :users do
      resources :questions, only: [:show] do
        resources :answers
      end
    end
    resources :teams do
      resources :questions, only: [:index] do
        resources :answers, only: [:index, :show]
      end
    end

    get 'organizations/:organization_id/answers' => 'organizations#index'

    resources :organizations do
      resources :teams
    end

    resources :users do
      resource :team
    end
    resources :teams do
      resources :answers
    end
    resources :questions do
      resources :answers
    end
  end

  resources :organizations do
    resources :teams, only: [:index, :show]
  end

  resources :answers

  resources :questions do
    resources :answers
  end

  resources :teams do
    resources :questions
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :teams
  belongs_to :creator, class_name: "User"
  has_many :questions
  has_many :users, through: :teams
  has_many :answers, through: :questions

  validates :name, presence: true
  validates :start, presence: true
  validates_format_of :start, with: /([01]?[0-9]|2[0-3])\:[0-5][0-9]/
  validates :description, length: { maximum: 200 }
end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < ApiController
  def index
    @answers = Organization.find(params[:organization_id]).answers.last(10)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
    @teams = @organization.teams
    @last_answers = @organization.answers.last(10)
    @idList = []
    @teams.each do |t|
      @idList << t.id
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(new_organization_params)
    @organization.creator = current_user

    @q1 = Question.new(body: 'What did you work on yesterday?')
    @q2 = Question.new(body: 'What did you finish yesterday?')
    @q3 = Question.new(body: 'What are you working on today?')
    @organization.questions << [@q1, @q2, @q3]

    if @organization.save
      flash[:notice] = @organization.name + ' Added!'
      redirect_to @organization
    else
      flash[:alert] = 'Something went wrong. Please try again!'
      render :new
    end
  end

  protected

  def new_organization_params
    params.require(:organization).permit(:name, :description, :start)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_team_activity.erb
<div class="row">

<% @teams.each do |t| %>
<%if !t.answers.last.nil?%>
  <% tid = t.answers.last.id%>
<% else %>
  <% tid = '0' %>
<% end %>
<div class="columns medium-6">
  <h4 class="org-section"><%= "#{t.name} | #{t.time_readable}" %></h4>
  <div style="display:none" id=<%="hidden-team-answer-id-#{t.id}"%> ><%= tid %></div>
  <div class="org-answers" id=<%="org-team-#{t.id}" %> >
    <% t.answers.last(5).reverse.each do |a| %>
      <div class="user-response">
        <div class="left-section">
          <%= link_to a.user.fullname, "mailto:#{a.user.email}" %>
          <%= a.submitter_time + " there | " + a.viewer_time(current_user.local_zone) +" here" %>
        </div>
        <div class="right-section">
          <span class="team-question"><%= a.question.body %></span>
          <span class="team-answer"><%= a.body %></span>
        </div>
      </div>
    <% end %>
  </div>
  </div>
<% end %>
</div>

app/views/organizations/index.html.erb
<h1> test </h1>

app/views/organizations/new.html.erb
<div class="master-form">

<h1 class ="form-title">Create an Organization</h1>

<%= form_for @organization do |f| %>
    <div class="field">
      <%= f.label :name, class: 'form-text'%>
      <p class="form-instructions">Your company or organization name.</p>
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :start, "Standup Time", class: 'form-text'%>
      <p class="form-instructions"> This is when all users in your organization will start. Please enter as 12-hour with am/pm (i.e. 9:00 am), or as 24-hour time without it (i.e. 14:00).</p>
      <%= f.text_field :start, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :description, "Description", class: 'form-text'%>
        <p class="form-instructions">Completely optional. Don't worry, you can change this later.</p>
      <%= f.text_field :description, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Create", class: 'button radius' %>
    </div>
  <% end %>

</div>

app/views/organizations/show.html.erb
<div class="org-wrapper">

<h1 class="org-name"><%= @organization.name %></h1>

<div class="switch-links">
  <a href="#" onclick="toAll()">All Teams</a> |
  <a href="#" onclick="toSpecific()">Answers by Team</a>
</div>

<div id="specific-teams" class="team-activity row">
  <%= render "team_activity" %>
</div>

<div style="display:none" id="org-id"><%= @organization.id %></div>
<div id="hidden-id" style="display:none"><%= @last_answers.last.id if !@last_answers.last.nil? %></div>

<div id="all-teams" style="display:none">
  <div class="org-activity-appendable" id="org-activity-appendable">
    <% @last_answers.each do |a| %>
    <div class="user-response">
      <div class="left-section">
        <%= link_to a.user.fullname, "mailto:#{a.user.email}" %>
        <%= a.submitter_time + " there | " + a.viewer_time(current_user.local_zone) +" here" %>
      </div>
      <div class="right-section">
        <span class="team-question"><%= a.question.body %></span>
        <span class="team-answer"><%= a.body %></span>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= link_to "New Organization", new_organization_path %><br />

<%= link_to "All Teams in #{@organization.name}", organization_teams_path(@organization) %>
</div>