config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'users#index'

  namespace :api do
    resources :users do
      resources :questions, only: [:show] do
        resources :answers
      end
    end
    resources :teams do
      resources :questions, only: [:index] do
        resources :answers, only: [:index, :show]
      end
    end

    get 'organizations/:organization_id/answers' => 'organizations#index'

    resources :organizations do
      resources :teams
    end

    resources :users do
      resource :team
    end
    resources :teams do
      resources :answers
    end
    resources :questions do
      resources :answers
    end
  end

  resources :organizations do
    resources :teams, only: [:index, :show]
  end

  resources :answers

  resources :questions do
    resources :answers
  end

  resources :teams do
    resources :questions
  end
end

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
  <div class="row">
    <div class="small-12 columns sign-nav">
      <% if current_user %>
        <div class="nav-clock">
          <div id="user-time-zone" style="display:none"><%= current_user.team.time_zone.name %></div>
          <div id="user-time" class="nav-time"></div>
          <div class="timezone clearfix"><%= "#{current_user.team.location}" %></div>
        </div>
      <% end %>
      <h3 class="logo"><%= link_to "STANDDOWN", root_path %></h3>
      <% if user_signed_in? %>
        <%= link_to("Sign Out", destroy_user_session_path, method: :delete,
          class: "sign-links user-signs") %>
        <%= link_to(current_user.team.name, team_path(current_user.team),
        class: "sign-links user-signs") %>
        <%= link_to(current_user.team.organization.name, organization_path(current_user.team.organization),
          class: "sign-links user-signs") %>
      <% else %>
        <%= link_to("Sign Up", new_user_registration_path,
          class: "sign-links user-signs") %>
        <%= link_to("Sign In", new_user_session_path,
          class: "sign-links user-signs") %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "StandDown" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div id="app" ></div>
    <div class="container">
     <% flash.each do |key, value| %>
      <div id="flash" class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
    </div>
  <%= yield %>
  </body>
</html>